core-it-suite/pom.xml, core-it-suite/src/test/java/org/apache/maven/it/IntegrationTestSuite.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4660OutdatedPackagedArtifact.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4660ResumeFromTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6090CIFriendlyTest.java, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/module-a/pom.xml, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/module-a/src/main/java/org/apache/maven/it/Example.java, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/module-b/pom.xml, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/module-b/src/main/java/org/apache/maven/it/AnotherExample.java, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/module-b/src/test/java/org/apache/maven/it/TestCase.java, core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/pom.xml, core-it-suite/src/test/resources/mng-4660-resume-from/module-a/pom.xml, core-it-suite/src/test/resources/mng-4660-resume-from/module-a/src/main/java/org/apache/maven/it/Example.java, core-it-suite/src/test/resources/mng-4660-resume-from/module-b/pom.xml, core-it-suite/src/test/resources/mng-4660-resume-from/module-b/src/main/java/org/apache/maven/it/AnotherExample.java, core-it-suite/src/test/resources/mng-4660-resume-from/module-b/src/test/java/org/apache/maven/it/TestCase.java, core-it-suite/src/test/resources/mng-4660-resume-from/pom.xml
Will offer this one for merging once the bug has indeed been fixed, and the `// TODO` regarding the version range has been resolved.
=> [MNG-4660] Add integration test to show that --resume-from works

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7051OptionalProfileActivationTest.java
Needed for https://github.com/apache/maven/pull/453
=> [MNG-7051] When an optional profile could not be found, an info message should be thrown instead of a warning.

core-it-suite/src/test/resources/mng-5840-relative-path-range-negative/child/pom.xml, core-it-suite/src/test/resources/mng-5840-relative-path-range-positive/child/pom.xml, core-it-suite/src/test/resources/mng-5840-relative-path-reactor-matching/child/pom.xml
To IT test maven3/4 we should not use lower than
3.x plugin (that is maven2 compat)
=> Up enforcer version

core-it-suite/src/test/resources/mng-4660-outdated-packaged-artifact/pom.xml, core-it-suite/src/test/resources/mng-4660-resume-from/pom.xml, core-it-suite/src/test/resources/mng-5760-resume-feature/four-modules/pom.xml, core-it-suite/src/test/resources/mng-5760-resume-feature/parent-dependent/pom.xml, core-it-suite/src/test/resources/mng-5760-resume-feature/parent-independent/pom.xml, core-it-suite/src/test/resources/mng-6118-submodule-invocation-full-reactor/pom.xml, core-it-suite/src/test/resources/mng-6511-optional-project-selection/pom.xml, core-it-suite/src/test/resources/mng-6972-allow-access-to-graph-package/build-plugin/pom.xml, core-it-suite/src/test/resources/mng-6981-pl-should-include-children/pom.xml, core-it-suite/src/test/resources/mng-7045/pom.xml, core-it-suite/src/test/resources/mng-7128-block-external-http-reactor/pom.xml
See discussion here: https://github.com/apache/maven-integration-testing/pull/135#discussion_r787104645.
=> Set Maven compiler and release versions to 7 for integration test projects

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java
Seems the test must be forked to work in, as it fails to work
in embedded mode.
=> Fix the MavenITmng7470ResolverTransportTest

core-it-suite/src/test/java/org/apache/maven/it/HttpServer.java
The HttpServer helper is used by two ITs:
* MavenITmng7470ResolverTransportTest
* MavenITmng5771CoreExtensionsTest
And it logs in case of MNG7470 for unknown reason. My bet would
be some static initing happening as side effect of OTHER ITs that
use Jetty directly, like MavenITmng5868NoDuplicateAttachedArtifacts.
Anyway, this sorts out Jetty logging.
=> Mute Jetty

core-it-suite/src/test/java/org/apache/maven/it/HttpServer.java
Fix for #159
Jetty logger not always is `StdErrLog` can be eg. `Slf4jLog`
=> Fix - mute Jetty

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7353CliGoalInvocationTest.java, core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7353-cli-goal-invocation/pom.xml
Add missing dependencies to bootstrap.txt instead of changing the test internal versions (reverts 8dd42243ecf74c26d4a2788e7871e660eef77115).
=> [MNG-7353] Add missing dependencies to bootstrap.txt

core-it-suite/src/test/resources-filtered/bootstrap.txt
maven-plugin-api:3.2.5, sisu-maven-plugin:0.3.5 are used eg. in  mng7474 
it causes errors with empty local repo - from time to time 😄 
example last build on 3.9.x https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven/job/maven-3.9.x/
=> Add missing artifacts for tests to bootstrap

core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
- basedir can be null when test is executed by IDE, use default value
- use try-with-resources
=> Allow basedir system property to be null for build info.txt

.github/workflows/maven-verify.yml
Old actions use deprecated node 12
- checkout v2 -> v3
- setup-java v2 -> v3
- disable access to GITHUB_TOKEN
- don't store credentials with checkout
=> Update actions in GH build

core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7045/pom.xml
This should be the only change needed to run the tests on JDK 19. Tested with Maven 3.8.7 and latest master as of today (4.0.0-alpha-4-SNAPSHOT):
* `mvn clean install -Prun-its -Dmaven.repo.local=$(pwd)/repo `
* `mvn clean install -Prun-its -Dmaven.repo.local=$(pwd)/repo -Dmaven.home=<path-to-maven-git-repo>/apache-maven/target/apache-maven-4.0.0-alpha-4-SNAPSHOT`
=> Upgrade Groovy in one of the ITs to support JDK 19

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7112ProjectsWithNonRecursiveTest.java
@hboutemy here is the fix for the broken IT.
The reason it did not fail during a PR build in this repo (https://github.com/apache/maven-integration-testing/pull/225) is that we are not running PR builds with Maven 4, just latest 3.x (as far as I know). 
Maybe something that could be improved? Adding a build with latest Maven SNAPSHOT from master?
=> [MNG-7661] Fix verifier 'clean' call in one of the ITs

core-it-suite/pom.xml, core-it-suite/src/test/java/org/apache/maven/it/HttpServer.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0553SettingsAuthzEncryptionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng1895ScopeConflictResolutionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3953AuthenticatedDeploymentTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4068AuthenticatedMirrorTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4235HttpAuthDeploymentChecksumsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4413MirroringOfDependencyRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4469AuthenticatedDeploymentToCustomRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4470AuthenticatedDeploymentToProxyTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4489MirroringOfExtensionRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4561MirroringOfPluginRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4729MirrorProxyAuthUsedByProjectBuilderTest.java
Update Jetty to latest 9.4.50, last Java 8 capable version. Apply API changes and also remove jetty-servlet as ITs does NOT use servlet aspect of Jetty HTTP server.. This will simplify our lives in future, to make jump to later versions (that are Java 11+). Also, drop jetty-servlet as test do not use any servlet aspect.
---
https://issues.apache.org/jira/browse/MNG-7665
=> [MNG-7665] Update Jetty to latest Java8 capable version

pom.xml
A parent POM have it removed, but the plgMgmt does not have this entry of IT project.
=> Fix plexus-component-metadata plugin version

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0828PluginConfigValuesInDebugTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5175WagonHttpTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5214DontMapWsdlToJar.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5230MakeReactorWithExcludesTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5581LifecycleMappingDelegate.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5895CIFriendlyUsageWithPropertyTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5965ParallelBuildMultipliesWorkTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6057CheckReactorOrderTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6090CIFriendlyTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6391PrintVersionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6656BuildConsumer.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6957BuildConsumer.java
@slawekjaranowski @michael-o hey again, this is the last one of these verifier PRs, and actually pretty small and trivial to review (and I already had it ready for some time).
* `verifier.setMavenDebug( false );` is the default, so there is actually no need to have it (not mentioning, there is no direct replacement for this in the new API -- the replacement is to _not_  add the `-X` argument).
=> [MNG-7661] Replace deprecated 'verifier.setMavenDebug()'

core-it-support/maven-it-plugin-bootstrap/src/main/java/org/apache/maven/its/bootstrap/DownloadMojo.java
The m-p-p depends on m-p-tools-ant and m-p-tools-beanshell as runtime/optional, and the way DownloadMojo resolves every artifact causes that OptionalDependencySelector filter these out even at "collection" stage (as depth >= 2).
Hence, fix DownloadMojo to resolve properly, that actually shifts all the tree "one level up", and hence result is same as in Maven, as the optional dependencies become "first level sibling".
---
https://issues.apache.org/jira/browse/MNG-7667
=> [MNG-7667] Fix DownloadMojo to properly resolve

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java
If 3.9 uses native as default as well, there is no need anymore to distinguish between 3.9 and 4+.
---
https://issues.apache.org/jira/browse/MNG-7608
=> [MNG-7608] Adjust IT for default transport

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4305LocalRepoBasedirTest.java, core-it-suite/src/test/resources/mng-4305/pom.xml, core-it-support/core-it-plugins/maven-it-plugin-expression/src/main/java/org/apache/maven/plugin/coreit/EvalMojo.java
The MNG-7706 deprecates ancient ArtifactRepository type use to get access to local repository, and issues warning as for any other deprecated Mojo parameters.
But alas, in ITs the MNG-5576 completely unrelated IT there is an assertion to have WARNING-free log. This IT uses the IT-plugins/IT-plugin-expression EvalMojo, that in turn uses the deprecated `${localRepository}` parameter (but does not use it). Result is, Maven 3.9.1 emits a WARNING about use of deprecated parameter and the IT fails.
Further inspection shows, that while EvalMojo injects ArtifactRepository for local repository, there is only one IT that actually uses it, the MNG-4305, but even that one is interested in basedir of the local repository only. So to say, the use of deprecated ArtifactRepository type is not needed at …
=> [MNG-7706] Fix for ITs

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7128BlockExternalHttpReactorTest.java
Related IT change, as the change for this issue made MNG-7128 IT to fail, as it was too eagerly matching whole error message string that has now due MNG-5181 changed.
To fix it, match only the key parts of the expected error message, that project failed, due transfer failure, as insecure mirror was blocked. This makes IT assert same thing, but is more flexible regarding error text change in MNG-5181.
---
Context: the modified IT fails in this PR https://github.com/apache/maven/pull/1025 as Resolver 1.9.6 carries extra information about artifact availability in the message, that makes the IT full string match fail now.
---
https://issues.apache.org/jira/browse/MNG-5185
=> [MNG-5181] Improve "missing dependency" message

core-it-suite/pom.xml, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4356NoNeedlessRelookupFromActiveCollectionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4565MultiConditionProfileActivationTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4761PluginLevelDependencyScopesTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5206PlexusLifecycleHonoured.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5418FileProjectPropertiesActivatorTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5503ZipInReactorTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5557ProperlyRestrictedReactor.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
Even test is skipped by `@Disabled` annotation
newer surefire schedule it for execution.
When tests are missing in TestSuiteOrdering
are executed as one of first tests in unpredictable order.
We have many options:
- left as is
- show info as in PR
- break a build
=> Detecting tests which was not added to TestSuiteOrdering

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5222MojoDeprecatedTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7464ReadOnlyMojoParametersWarningTest.java
Fixed ITs to not fail:
- assert only for content, neglect and possible indentation
- do not assert what is NOT warn logged, as later we may log more (IT would be not future proof)
Tested with 3.9.1 and 3.9.2-SNAPSHOT w/ https://github.com/apache/maven/pull/1079 Both passes OK
MNG-7754 changes how plugin validation errors are reported (at end and as a dense report), so ITs needs a bit of lax re formatting and indentation and such.
---
https://issues.apache.org/jira/browse/MNG-7754
=> [MNG-7754] Improve plugin validation

core-it-support/core-it-plugins/maven-it-plugin-core-stubs/maven-resources-plugin/pom.xml
The MavenITmng6562WarnDefaultBindings IT tests new Maven4 feature "fail on severity" (for WARN level).
The stub core plugin maven-resources-plugin depends on maven-compat, and it emits plugin validation warning.
BEFORE MNG-7788 was merged, the warnings were logged AFTER build summary and was not picked up by "fail on severity".
AFTER MNG-7788 merged, it causes that warnings breaks the build, as "fail on severity" is set to WARN level.
Fix:
The stub maven-resources-plugin does NOT need to depend on maven-compat, what it really needs is maven-core (for MavenProject).
=> [MNG-7788] Fix for IT MavenITmng6562WarnDefaultBindings

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0768OfflineModeTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4348NoUnnecessaryRepositoryAccessTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4500NoUpdateOfTimestampedSnapshotsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4554PluginPrefixMappingUpdateTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4772PluginVersionResolutionDoesntTouchDisabledRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5064SuppressSnapshotUpdatesTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6057CheckReactorOrderTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6391PrintVersionTest.java, core-it-suite/src/test/resources/mng-3203/src/main/java/org/apache/maven/it/mng3203/App.java, core-it-suite/src/test/resources/mng-5581-lifecycle-mapping-delegate/extension/src/main/java/org/apache/maven/its/mng5581/lifecyclemappingdelegate/TestLifecycleMappingDelegate.java
As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu
=> [MNG-6847] Use diamond operator

core-it-suite/src/test/resources/mng-3203/pom.xml, core-it-suite/src/test/resources/mng-7045/pom.xml, core-it-suite/src/test/resources/mng-7128-block-external-http-reactor/pom.xml
=> Use 1.8 for source/target in ITs - allow to execute by newer JDK

core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7836-alternative-pom-syntax/maven-hocon-extension/pom.xml
Current Maven master is broken due to the dependency on 4.0.0-alpha-8-SNAPSHOT which are not built anymore, see https://github.com/apache/maven/actions/runs/6767772744/job/18391037312?pr=1297
=> Use 4.0.0-alpha-8 instead of SNAPSHOT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4368TimestampAwareArtifactInstallerTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5175WagonHttpTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java, core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/AbstractMavenIntegrationTestCase.java
Changes:
* IT MNG-4368 "smart install" undone
* IT MNG-5175 force Wagon as it uses Wagon config
* IT MNG-7470 adapt to new default and new transport
=> [MNG-7909] Apply Resolver 2.0.0 changes

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2741PluginMetadataResolutionErrorMessageTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java
I was unaware that for master Maven 3.9.x is used. So the original commit 69ecbafa9903f6c171a1413623bbed16177712ef does not work with 3.9.x, this PR fixes it.
=> Fix ITs master build

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7965PomDuplicateTagsTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-7965-pom-duplicate-tags/pom.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-7965
Main PR: https://github.com/apache/maven/pull/1344
- [MNG-7965] Verify non-parseable POM is detected
- Remove unused
- Adjust maven range
- Fix test
=> [MNG-7965] Verify non-parseable POM is detected

core-it-suite/pom.xml
As currently used one is plagued with CVEs etc.
As long as we are stuck on Java8, we cannot move forward with Jetty, as Jetty 10.x (that is drop in replacement) is Java 11.
=> Update Jetty to 9.4.53.v20231009

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7967ArtifactHandlerLanguageTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7967-artifact-handler-language/pom.xml, core-it-suite/src/test/resources/mng-7967-artifact-handler-language/src/main/java/org/apache/maven/its/mng7967/Sample.java
It uses javadoc:jar goal from locked-down version of Javadoc plugin: Bug is that it refuses to run as 4-alpha-9 returns here language="none". If it would run, it would explode, as project contains java source with intentionally broken javadoc.
---
https://issues.apache.org/jira/browse/MNG-7967
=> [MNG-7967] Verify javadoc:jar is invoked

core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/parent/1.0.0-SNAPSHOT/parent-1.0.0-20221014.203717-12.pom
The goal of IT is to "exercise file locking with snapshots" and not to test model validation.
The IT used dependency had an invalid parent POM w/ wrong packaging.
See IT issue: https://issues.apache.org/jira/browse/MNG-7819
=> Fix MNG-7819 IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java
Old output:
```
[ERROR] Failed to execute goal on project test: Could not resolve dependencies for project org.apache.maven.its.mng3477:test:jar:1: Failed to collect dependencies at org.apache.maven.its.mng3477:dep:jar:1.0: Failed to read artifact descriptor for org.apache.maven.its.mng3477:dep:jar:1.0: The following artifacts could not be resolved: org.apache.maven.its.mng3477:dep:pom:1.0 (absent): Could not transfer artifact org.apache.maven.its.mng3477:dep:pom:1.0 from/to maven-core-it (http://localhost:54312/repo): Connection to http://localhost:54312/repo/ refused: ConnectException: ClosedChannelException -> [Help 1]
```
new:
```
[ERROR] Failed to execute goal on project test: Could not collect dependencies for project org.apache.maven.its.mng3477:test:jar:1
[ERROR] Failed to read …
```
=> [MNG-7758] Report dependency problems for all repository - fix IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3043BestEffortReactorResolutionTest.java, core-it-suite/src/test/resources-filtered/bootstrap.txt
JIRA issue: https://issues.apache.org/jira/browse/MNG-7838
Main PR: https://github.com/apache/maven/pull/1199
=> [MNG-7838] Fix IT and add another one

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3863AutoPluginGroupIdTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7255InferredGroupIdTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-7255-inferred-groupid/child/pom.xml, core-it-suite/src/test/resources/mng-7255-inferred-groupid/dep/pom.xml, core-it-suite/src/test/resources/mng-7255-inferred-groupid/pom.xml
Main PR: https://github.com/apache/maven/pull/1696
=> [MNG-7255] Infer groupId for intra-reactor dependencies

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8230CIFriendlyTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-project-props/child/pom.xml, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-project-props/pom.xml, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-user-props/child/pom.xml, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/cif-with-user-props/pom.xml, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/exp-in-artifactid/pom.xml, core-it-suite/src/test/resources/mng-8230-ci-friendly-and-gav/exp-in-groupid/pom.xml
Main PR: https://github.com/apache/maven/pull/1710
=> [MNG-8230] Add tests for CI-friendly versions

core-it-suite/pom.xml, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0553SettingsAuthzEncryptionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5774ConfigurationProcessorsTest.java, core-it-suite/src/test/resources-filtered/bootstrap.txt
Also minor fix, but MavenITmng8220ExtensionWithDITest needs slf4j-api 2.0.16 that is not in bootstrap.
---
https://issues.apache.org/jira/browse/MNG-8267
=> [MNG-8267] Disable MNG-5774 ITs for beta-5+
