apache/maven-integration-testing

core-it-suite/src/test/java/org/apache/maven/it/IntegrationTestSuite.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2309ProfileInjectionOrderTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3641ProfileActivationWarningTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3732ActiveProfilesTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4106InterpolationUsesDominantProfileTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7051OptionalProfileActivationTest.java, core-it-suite/src/test/resources/mng-7051-optional-profile-activation/pom.xml
Integration tests for [MNG-7051](https://issues.apache.org/jira/browse/MNG-7051). Some are duplicated (a pre-4.0.0 and a post-4.0.0 version) because the behaviour has changed in a breaking way.
=> [MNG-7051] Test activation of non-existing profiles

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5771CoreExtensionsTest.java, core-it-suite/src/test/resources/mng-5771-core-extensions/client-config/.mvn/extensions.xml, core-it-suite/src/test/resources/mng-5771-core-extensions/client-config/.mvn/maven.config, core-it-suite/src/test/resources/mng-5771-core-extensions/client-config/pom.xml, core-it-suite/src/test/resources/mng-5771-core-extensions/client-properties/.mvn/extensions.xml, core-it-suite/src/test/resources/mng-5771-core-extensions/client-properties/pom.xml
This is a testcase for
- https://github.com/apache/maven/pull/673
- https://github.com/apache/maven/pull/665
=> MNG-7395 - add a test with properties in extensions.xml

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng0828PluginConfigValuesInDebugTest.java
* Make datetime parsing Locale independent.
=> Fix [MNG-828]

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5222MojoDeprecatedParamsTest.java, core-it-support/core-it-plugins/maven-it-plugin-configuration/src/main/java/org/apache/maven/plugin/coreit/DeprecatedConfigMojo.java
for https://github.com/apache/maven/pull/722
=> [MNG-5222] Improvement in deprecated params detection

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java
To cover the default case as well (nothing set), and make sure
Wagon is used.
Related to https://github.com/apache/maven/pull/739
=> Extend MavenITmng7470ResolverTransportTest

core-it-suite/pom.xml, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3652UserAgentHeaderTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4528ExcludeWagonsFromMavenCoreArtifactsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5669ReadPomsOnce.java, core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-3599-mk2/pom.xml, core-it-suite/src/test/resources/mng-3599/pom.xml, core-it-suite/src/test/resources/mng-3652/test-plugin/pom.xml, core-it-suite/src/test/resources/mng-3652/test-project/pom.xml, core-it-suite/src/test/resources/mng-5669-read-poms-once/pom.xml, core-it-suite/src/test/resources/mng-7470-resolver-transport/project/pom.xml
* Disable unused tests
* Update Maven 2 plugins to Maven 3 to avoid conflicts with old Maven
and Wagon 1
=> [MNG-7020] Remove Maven 2 WagonExcluder backward compat code

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3057VersionExprTransformationsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3268MultipleHyphenPCommandLineTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3545ProfileDeactivationTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3641ProfileActivationWarningTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3714ToolchainsCliOptionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4428FollowHttpRedirectTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5208EventSpyParallelTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5338FileOptionToDirectory.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5557ProperlyRestrictedReactor.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5578SessionScopeTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5716ToolchainsTypeTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6090CIFriendlyTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6118SubmoduleInvocation.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6511OptionalProjectSelectionTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7128BlockExternalHttpReactorTest.java
Prepare for Verifier 2.0 - MSHARED-1125
=> Add cli arguments one by one for Verifier

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5530MojoExecutionScopeTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5771CoreExtensionsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5774ConfigurationProcessorsTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5889FindBasedir.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6071GetResourceWithCustomPom.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6210CoreExtensionsCustomScopesTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6255FixConcatLines.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6256SpecialCharsAlternatePOMLocation.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6772NestedImportScopeRepositoryOverride.java, core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/AbstractMavenIntegrationTestCase.java
Follow up to ecf4a04cd1c4b7698f28e3332cd24c23116c1467 which missed a few tests using the above pattern
=> Remove verifier.getCliOptions().add( x ) pattern

core-it-suite/src/test/resources-filtered/bootstrap.txt
Causes failing tests on 3.9.x branch
=> Add org.apache.maven.plugins:maven-plugin-plugin:3.2 to bootstrap

core-it-suite/src/test/java/org/apache/maven/it/IntegrationTestSuite.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7310LifecycleActivatedInSpecifiedModuleTest.java, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/extension/pom.xml, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/extension/src/main/java/testmojo/TestMojo.java, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/extension/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/extension/src/main/resources/META-INF/plexus/components.xml, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/project/extension-user/pom.xml, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/project/other-module/pom.xml, core-it-suite/src/test/resources/mng-7310-lifecycle-activated-in-specified-module/project/pom.xml
The test installs an extension and then builds a multimodule project where one submodule activates the extension, and a submodule which should not activate the extension.
=> [MNG-7310] Add a test for MNG-7310

core-it-suite/src/test/java/org/apache/maven/it/IntegrationTestSuite.java, core-it-suite/src/test/java/org/apache/maven/it/ItUtils.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6981ProjectListShouldIncludeChildrenTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7568SettingsProfileDeactivationTest.java, core-it-suite/src/test/resources/mng-7568-inactive-profile-deactivation/pom.xml, core-it-suite/src/test/resources/mng-7568-inactive-profile-deactivation/settings.xml
For
- https://github.com/apache/maven/pull/809
=> [MNG-7568] Test for deactivating profile defined in settings and project

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7606DependencyImportScopeTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7606/pom.xml
https://issues.apache.org/jira/browse/MNG-7606
=> [MNG-7606] add IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5669ReadPomsOnce.java
In test, we check if pom files are read only once.
When we update plugin or dependencies in test,
number of read items can change again.
So should be good enough to check if duplicate items exist in log file.
=> Fix MavenITmng5669ReadPomsOnce

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4470AuthenticatedDeploymentToProxyTest.java
This IT helped a lot to figure out problems around parallel deploy, and I had locally applied these changes to improve ability to track down what is actually happening on server side.
=> No logic change, just improve logging

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7737ProfileActivationTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources-filtered/bootstrap.txt, core-it-suite/src/test/resources/mng-7737-profiles/pom-file1.txt, core-it-suite/src/test/resources/mng-7737-profiles/pom.xml, core-it-suite/src/test/resources/mng-7737-profiles/settings-file1.txt, core-it-suite/src/test/resources/mng-7737-profiles/settings.xml
Just a simple IT that would catch issues like Maven 3.9.0 went out with, where files were wrongly interpolated: MNG-7726
---
https://issues.apache.org/jira/browse/MNG-7737
=> [MNG-7737] IT for profiles

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3843PomInheritanceTest.java
Main PR: https://github.com/apache/maven/pull/1085
=> [MNG-7763] Provide UTF-8 as a default value for project.build.sourceEncoding and project.reporting.outputEncoding

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4461ArtifactUploadMonitorTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4829ChecksumFailureWarningTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6240PluginExtensionAetherProvider.java
Relevant [Maven PR](https://github.com/apache/maven/pull/869)
=> [MNG-7338] Disable CI mode for certain tests which verify on log statements.

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5600DependencyManagementImportExclusionsTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-5600/exclusions/pom.xml, core-it-suite/src/test/resources/mng-5600/repo/org/apache/maven/its/mng5600/bom/0/bom-0.pom, core-it-suite/src/test/resources/mng-5600/settings-template.xml
Supersedes #30 and #59
Maven PR: https://github.com/apache/maven/pull/1155
=> [MNG-5600] Dependency management import should support exclusions.

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3748BadSettingsXmlTest.java, core-it-suite/src/test/resources/mng-3748/settings.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-4645
IT for https://github.com/apache/maven/pull/1139
=> [MNG-4645] Fix IT to not use the newly supported syntax

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7819FileLockingWithSnapshotsTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/pom.xml, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/dependency/1.0.0-SNAPSHOT/dependency-1.0.0-20221014.203717-12.jar, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/dependency/1.0.0-SNAPSHOT/dependency-1.0.0-20221014.203717-12.pom, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/dependency/1.0.0-SNAPSHOT/maven-metadata.xml, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/parent/1.0.0-SNAPSHOT/maven-metadata.xml, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/repo/org/apache/maven/its/mng7819/parent/1.0.0-SNAPSHOT/parent-1.0.0-20221014.203717-12.pom, core-it-suite/src/test/resources/mng-7819-file-locking-with-snapshots/settings-template.xml
Template/reproducer: https://gist.github.com/cstamas/3f15775bd4785a5f4b157399f52af6fc
While local repo is empty.
---
https://issues.apache.org/jira/browse/MNG-7819
=> [MNG-7819] Add IT that excercise the bug

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng1803PomValidationErrorIncludesLineNumberTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3748BadSettingsXmlTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5576CdFriendlyVersions.java, core-it-suite/src/test/resources/mng-6656-buildconsumer/expected/parent.pom, core-it-suite/src/test/resources/mng-6656-buildconsumer/expected/simple-parent.pom, core-it-suite/src/test/resources/mng-6656-buildconsumer/expected/simple-weather.pom, core-it-suite/src/test/resources/mng-6656-buildconsumer/expected/simple-webapp.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/parent.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/simple-parent.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/simple-testutils.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/simple-weather.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/simple-webapp.pom, core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/utils-parent.pom
- Fix ITs
- Add debug info
- Ignore warnings at the beginning of the build caused by https://github.com/actions/setup-java/pull/503/
- Fix parser using beginning of tag to report errors
- Fix spotless
=> [MNG-7830] Switch from plexus-xml to stax / woodstox

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6401ProxyPortInterpolationTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-6401-proxy-port-interpolation/pom.xml, core-it-suite/src/test/resources/mng-6401-proxy-port-interpolation/settings.xml
JIRA issue: https://issues.apache.org/jira/browse/MNG-6401
Main PR: https://github.com/apache/maven/pull/1194
=> [MNG-6401] IT for proxy port interpolation

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2741PluginMetadataResolutionErrorMessageTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java
To recognize new error message coming from JDK transport.
Message is to be improved with https://issues.apache.org/jira/browse/MRESOLVER-429
=> [MNG-7909] IT changes

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7939PluginsValidationExcludesTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-7939-plugins-validation-excludes/pom.xml, core-it-support/core-it-plugins/maven-it-plugin-configuration/src/main/java/org/apache/maven/plugin/coreit/LocalRepoMojo.java
(cherry picked from commit 56bd8fc23b7a426f357f5129a1d6d05feee5f53c)
=> [MNG-7939] Allow to exclude plugins from validation

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2741PluginMetadataResolutionErrorMessageTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng7470ResolverTransportTest.java
Changes:
* transport renames
* some internals rename
=> Preparations for resolver alpha-3

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6127PluginExecutionConfigurationInterferenceTest.java
I can't reproduce the unstable 6127 IT in the local environment. With the debug log enabled, I will try to troubleshoot the problem through the debug log.
=> Enables debug logs in MavenITmng6127

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng1088ReactorPluginResolutionTest.java
IT PR for https://github.com/apache/maven/pull/1330
=> Disable MNG-1088 test for MNG-7977

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8106OverlappingDirectoryRolesTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8106/jar/pom.xml, core-it-suite/src/test/resources/mng-8106/plugin/pom.xml, core-it-suite/src/test/resources/mng-8106/plugin/src/main/java/org/apache/maven/its/plugins/MavenPlugin.java
Created IT that does "wrong" (as same directory has once G and once A role), and verify that both level metadata is present. In other words, but none is dropped.
---
https://issues.apache.org/jira/browse/MNG-8106
=> [MNG-8106] IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8106OverlappingDirectoryRolesTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8106/jar/pom.xml, core-it-suite/src/test/resources/mng-8106/plugin/pom.xml, core-it-suite/src/test/resources/mng-8106/plugin/src/main/java/org/apache/maven/its/plugins/MavenPlugin.java
Created IT that does "wrong" (as same directory has once G and once A role), and verify that both level metadata is present. In other words, but none is dropped.
---
https://issues.apache.org/jira/browse/MNG-8106
=> [3.9.x] [MNG-8106] IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java
(cherry picked from commit f0269bc6b3e05ac828ae227e70c80d5e6c581987)
=> [MNG-7758] Report dependency problems for all repository - fix IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3477DependencyResolutionErrorMessageTest.java, core-it-suite/src/test/resources/mng-3477/pom-plugin.xml, core-it-suite/src/test/resources/mng-3477/settings-template.xml
(cherry picked from commit aaf6d01bf23b0c739f0daf970307d61a39e5b276)
=> [MNG-7758] Report dependency problems for all repository - extends ITs

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8181CentralRepoTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8181-central-repo/install-settings.xml, core-it-suite/src/test/resources/mng-8181-central-repo/pom.xml, core-it-suite/src/test/resources/mng-8181-central-repo/settings.xml
IT for https://github.com/apache/maven/pull/1615
=> [MNG-8181] Add IT for maven.repo.central variable

core-it-suite/src/test/resources/mng-7038-rootdir/pom.xml
IT PR for https://github.com/apache/maven/pull/1687
=> [MNG-7897] Use project.rootDirectory

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3843PomInheritanceTest.java
Main PR: https://github.com/apache/maven/pull/1726
=> [MNG-8258] activate Reproducible Builds by default

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3843PomInheritanceTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8294ParentChecksTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8294-parent-checks/bad-mismatch/child/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/bad-mismatch/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/bad-non-resolvable/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/bad-wrong-path/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-empty/child/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-empty/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-gav/child/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-gav/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-path/child/pom.xml, core-it-suite/src/test/resources/mng-8294-parent-checks/ok-using-path/pom.xml
Main PR: https://github.com/apache/maven/pull/1784
=> [MNG-8294] Consistency checks when loading parent

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8299CustomLifecycleTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8299-custom-lifecycle/CustomLifecyclePlugin/pom.xml, core-it-suite/src/test/resources/mng-8299-custom-lifecycle/CustomLifecyclePlugin/src/main/java/com/nextmetaphor/plugin/mojo/CustomLifecyclePluginPhase1Mojo.java, core-it-suite/src/test/resources/mng-8299-custom-lifecycle/CustomLifecyclePlugin/src/main/resources/META-INF/plexus/components.xml, core-it-suite/src/test/resources/mng-8299-custom-lifecycle/CustomLifecycleProject/pom.xml
Main PR: https://github.com/apache/maven/pull/1802
=> [MNG-8299] IT for custom lifecycle phase ordering

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng4936EventSpyTest.java, core-it-suite/src/test/java/org/apache/maven/it/MavenITmng6558ToolchainsBuildingEventTest.java
Main PR: https://github.com/apache/maven/pull/1778
=> [MNG-8322] Use the new ToolchainsBuilder and SettingsBuilder

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8341DeadlockTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8341-deadlock/child1/pom.xml, core-it-suite/src/test/resources/mng-8341-deadlock/child2/pom.xml, core-it-suite/src/test/resources/mng-8341-deadlock/parent/pom.xml, core-it-suite/src/test/resources/mng-8341-deadlock/pom.xml
Main PR: https://github.com/apache/maven/pull/1843
=> [MNG-8341] Add IT

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8360SubprojectProfileActivationTest.java, core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java, core-it-suite/src/test/resources/mng-8360/.mvn/maven.config, core-it-suite/src/test/resources/mng-8360/module1/pom.xml, core-it-suite/src/test/resources/mng-8360/pom.xml, core-it-suite/src/test/resources/mng-8360/settings.xml
Main PR: https://github.com/apache/maven/pull/1852
=> [MNG-8360] IT for subproject profile activation

core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8347TransitiveDependencyManagerTest.java, core-it-suite/src/test/resources/mng-8347-bnd-plugin/pom.xml, core-it-suite/src/test/resources/mng-8347-quarkus-tls-registry/pom.xml
As original test is not the full story.
---
https://issues.apache.org/jira/browse/MNG-8347
=> [MNG-8347] Additional tests
